### ISSUE TITLE
needs more plinko

### ISSUE THREAD

**Issue by shiffman** [shiffman/randomizer#13]

**Comment by PatrickMurphy** [comment]
Here is my Version of Plinko: http://imgur.com/a/t2dzY Test it out: https://patrickmurphy.github.io/randomizer/
You can drop a Disc with the mouse and it bounces off Pegs, when it hits the floor and comes to a stop, it checks it's x position and determines the winner. Like the spinner you can remove the selected and restart.

Todo: 
- Design and Colors
- Scale peg column numbers by resolution so they are spaced some ratio to disc radius
- Tweak physics



- Moving pegs or portals that teleport it back near the top randomly?
- Sounds?
