### ISSUE TITLE
File_not_found

### ISSUE THREAD

**Issue by waldooo** [shiffman/randomizer#24]
Tried to run locally on google chrome and returned the following on the console:

Failed to load resource: net::ERR_FILE_NOT_FOUND cdnjs.cloudflare.com/ajax/libs/muicss/0.9.26/css/mui.min.css 
Failed to load resource: net::ERR_FILE_NOT_FOUND mui.min.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND p5.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND p5.dom.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND firebase.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND fonts.googleapis.com/css?family=Roboto:300,400,500,700

Seems like all the links are pointing to local files: 
file://cdnjs.cloudflare.com/ajax/libs/muicss/0.9.26/css/mui.min.css , file://cdnjs.cloudflare.com/ajax/libs/muicss/0.9.26/js/mui.min.js , file://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.14/p5.js , etc.

**Comment by katsully** [comment]
Created pull request that fixes this issue
https://github.com/shiffman/randomizer/pull/25

**Comment by shiffman** [comment]
This can also be fixed by running a local server! Thanks @katsully!
